// Generated by CoffeeScript 1.10.0

/*
  translate scroll
 */

(function() {
  var docWheelHandler, pageColorChange, pageTouchRecord, pageTranslateX, pageWheelFlag, projects;

  pageTranslateX = function(x) {
    var page, targetX;
    if (x == null) {
      x = '0';
    }
    page = document.getElementsByClassName('pageWrap')[0];
    targetX = "translateX(" + x + ")";
    console.log(targetX);
    return page.style.transform = targetX;
  };

  pageColorChange = function(color) {
    var body;
    body = document.getElementById('body');
    return body.style.backgroundColor = color;
  };

  pageTouchRecord = {
    startX: 0,
    startY: 0,
    endX: 0,
    endY: 0,
    pageX: 0
  };

  document.body.addEventListener('touchstart', (function(e) {
    var touchEvent;
    e.preventDefault();
    touchEvent = e['touches'][0];
    pageTouchRecord.startX = touchEvent.screenX;
    return pageTouchRecord.startY = touchEvent.screenY;
  }), false);

  document.body.addEventListener('touchmove', (function(e) {
    var touchEvent;
    e.preventDefault();
    touchEvent = e['touches'][0];
    pageTouchRecord.endX = touchEvent.screenX;
    return pageTouchRecord.endY = touchEvent.screenY;
  }), false);

  document.body.addEventListener('touchend', (function(e) {
    var backgroundColor, offsetX, pX;
    e.preventDefault();
    offsetX = pageTouchRecord.endX - pageTouchRecord.startX;
    if (Math.abs(offsetX) > 60) {
      if (offsetX > 0) {
        pageTouchRecord.pageX += 20;
        if (pageTouchRecord.pageX >= 0) {
          pageTouchRecord.pageX = 0;
        }
      } else {
        pageTouchRecord.pageX -= 20;
        if (pageTouchRecord.pageX < -80) {
          pageTouchRecord.pageX = 0;
        }
      }
      pageTranslateX(pageTouchRecord.pageX + "%");
      pX = pageTouchRecord.pageX;
      if (pX === 0) {
        backgroundColor = '#A1E354';
      }
      if (pX <= -20) {
        backgroundColor = '#22C3AA';
      }
      if (pX === -80) {
        backgroundColor = '#F5A623';
      }
      return pageColorChange(backgroundColor);
    } else {
      return null;
    }
  }), false);

  pageWheelFlag = false;

  docWheelHandler = function(e) {
    var backgroundColor, delta, pX;
    if (!pageWheelFlag) {
      delta = e.wheelDelta && (e.wheelDelta > 0 ? 1 : -1) || e.detail && (e.detail > 0 ? -1 : 1);
      if (delta > 0) {
        console.log('wheelup');
        pageTouchRecord.pageX += 20;
        if (pageTouchRecord.pageX >= 0) {
          pageTouchRecord.pageX = 0;
        }
      } else if (delta < 0) {
        console.log('wheeldown');
        pageTouchRecord.pageX -= 20;
        if (pageTouchRecord.pageX < -80) {
          pageTouchRecord.pageX = 0;
        }
      }
      pageWheelFlag = true;
      setTimeout(function() {
        return pageWheelFlag = false;
      }, 1000);
      pageTranslateX(pageTouchRecord.pageX + "%");
      pX = pageTouchRecord.pageX;
      if (pX === 0) {
        backgroundColor = '#A1E354';
      }
      if (pX <= -20) {
        backgroundColor = '#22C3AA';
      }
      if (pX === -80) {
        backgroundColor = '#F5A623';
      }
      return pageColorChange(backgroundColor);
    } else {
      return null;
    }
  };

  document.body.addEventListener('mousewheel', docWheelHandler);

  document.body.addEventListener('DOMMouseScroll', docWheelHandler);

  projects = document.getElementsByClassName('projectsWrap')[0];

  projects.addEventListener('mousewheel', function(e) {
    return e.stopPropagation();
  });

  projects.addEventListener('DOMMouseScroll', function(e) {
    return e.stopPropagation();
  });

}).call(this);
